apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: lol-bootcamp-tracker
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    dir /data
    appendonly yes
