name: Build Migration Docker CI

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - docker/Dockerfile
      - package.json
      - package-lock.json
      - docker/Dockerfile.migrate
      - workers.ts
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container

        - name: Build and push migration container
          uses: docker/build-push-action@v6
          with:
            context: ./
            file: ./docker/Dockerfile.migrate
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/lol-bootcamp-tracker:migrate